server:
  port: 8765


spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: Buy
          uri: http://localhost:8081/
          predicates:
            - Path=/**